"""add status column to students

Revision ID: 30385d0d8994
Revises: 7a64b1e9ca2d
Create Date: 2025-07-05 16:38:28.798609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30385d0d8994'
down_revision: Union[str, Sequence[str], None] = '7a64b1e9ca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'status')
    # ### end Alembic commands ###
